<a href="https://colab.research.google.com/github/potopinc/colab/blob/main/ML_05_06_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Часть 1 (Занятие 5)

## Знакомимся с pandas

Библиотека **pandas** — библиотека для работы с данными, которая содержит высокоуровневые структуры данных и методы манипуляции ими.  
Сегодня pandas считается стандартом индустрии анализа данных.

Название pandas происходит от panel data — «панельные данные», что в эконометрике означает многомерные структуры данных.

Основу составляют две структуры данных:

Series;  
DataFrame.

In [1]:
import pandas as pd
from pandas import Series, DataFrame

# не забываем про импорт уже знакомых библиотек
import numpy as np
import matplotlib.pyplot as plt

### Series

**Тип данных Series**

Series — это объект данных, похожий на одномерный массив, который содержит набор значений и соответствующий им массив меток-индексов.

In [5]:
# создайте простой объект Series из списка значений
l = [1, 2, 3, 4, -5]
obj = Series(l)
obj

0    1
1    2
2    3
3    4
4   -5
dtype: int64

In [7]:
# получите представление самого массива с помощью атрибута values
obj.values

array([ 1,  2,  3,  4, -5])

In [8]:
# получите представление индексов с помощью атрибута index
obj.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
# создайте "смысловые" индексы
obj.index = ['zero', 'one', 'two', 'three', 'four']
obj

zero     1
one      2
two      3
three    4
four    -5
dtype: int64

In [12]:
# ещё один способ создать Series
Series(l, index=['zero', 'one', 'two', 'three', 'four'])

zero     1
one      2
two      3
three    4
four    -5
dtype: int64

In [14]:
#Дан словарь: название архитектур нейронных сетей и их вес в мегабайтах. Создайте Series из словаря.

models = {
    "Xception": 88,
    "VGG16": 528,
    "ResNet50": 98,
    "InceptionV3": 92,
    "MobileNetV2": 14
}
obj_new = Series(models)
obj_new

Xception        88
VGG16          528
ResNet50        98
InceptionV3     92
MobileNetV2     14
dtype: int64

#### Доступ к элементам Series

In [17]:
# используйте доступ по нумерованному индексу
obj_new.iloc[3]

np.int64(92)

In [18]:
# используйте значение индекса для выборки элемента
obj_new['VGG16']

np.int64(528)

In [19]:
# используйте значение индекса для выборки элемента "через точку"
obj_new.VGG16

np.int64(528)

In [21]:
# используйте значения индекса для выборки нескольких элементов
obj_new['VGG16':'InceptionV3']

VGG16          528
ResNet50        98
InceptionV3     92
dtype: int64

In [22]:
# отфильтруйте массив с помощью логической операции (выберите модели с весом меньше 90)
obj_new[obj_new < 90]

Xception       88
MobileNetV2    14
dtype: int64

In [23]:
obj_new * 5

Xception        440
VGG16          2640
ResNet50        490
InceptionV3     460
MobileNetV2      70
dtype: int64

In [24]:
obj_new.value_counts()

88     1
528    1
98     1
92     1
14     1
Name: count, dtype: int64

#### Основные функции
`obj.apply(len)` — применение функции к каждому элементу.

`obj.sum()` — сумма элементов.

`obj.any(func)` — первый подходящий элемент.

`obj = obj + 5` — добавить к каждому элементу 5.

`obj = obj * 5` — умножить каждый элемент на 5.

`obj.isin(list)` — есть ли элемент в списке?

`obj.mean()` — среднее значение.

`obj.astype(dtype)` — каждый элемент привести к типу.

`obj.value_counts()` — посчитать количество каждого элемента.

#### Практика 1

Выполни задание с использованием Series.

Создай объект models:
- индексы — названия моделей;
- значения — вес модели в мегабайтах.

Используй следующие данные:

`["Xception", "ResNet50", "MobileNetV2"]`, `[88, 98, 14]`

In [25]:
#1 твой код
obj = Series([88, 98, 14], index=["Xception", "ResNet50", "MobileNetV2"])
obj

Xception       88
ResNet50       98
MobileNetV2    14
dtype: int64

In [26]:
#2 посчитай суммарный вес моделей Xception и ResNet50
obj.sum()

np.int64(200)

In [29]:
#3 придумай название и добавьте еще одну модель: например, myNetV3 42
obj['myNetV3'] = 42
obj

Xception        88.000000
ResNet50       120.222222
MobileNetV2     36.222222
myNetV3         42.000000
dtype: float64

In [30]:
#4 для всех моделей, вес которых кратен 14, прибавь средний вес всех моделей, делённый на 3
obj[obj % 14 == 0] +=  round(((obj.sum() / 3) / 3), 2)
obj

Xception        88.000000
ResNet50       120.222222
MobileNetV2     36.222222
myNetV3         73.830000
dtype: float64

### DataFrame

**Тип данных DataFrame**

DataFrame — это набор Series.

Можно сказать, что это таблица, где каждая строка и каждый столбец — Series.

Доступ возможен как к строкам, так и к столбцам.

In [31]:
# создадим рандомный DataFrame

algorithms = ['Linear Regression', 'Random Forest', 'SVM', 'XGBoost', 'Neural Net', 'KNN']
task_types = ['Classification', 'Regression', 'Clustering']
data_types = ['Tabular', 'Text', 'Image']

# значение рандома
np.random.seed(8)

data = {
    'model': np.random.choice(algorithms, size=10),
    'type': np.random.choice(task_types, size=10),
    'score': np.random.randint(1, 10, size=10),
    'train_time': np.round(np.random.uniform(0.5, 10, size=10), 1),
    'data_size': np.random.randint(1000, 10000, size=10),
    'data_type': np.random.choice(data_types, size=10)
}

# создаем DataFrame
df = pd.DataFrame(data)
df

               model            type  score  train_time  data_size data_type
0            XGBoost      Regression      3         9.8       1735   Tabular
1         Neural Net      Regression      3         1.7       2418      Text
2      Random Forest  Classification      7         3.6       9000     Image
3      Random Forest      Regression      9         1.2       2400     Image
4                KNN      Clustering      4         2.6       8771      Text
5                SVM  Classification      5         4.2       6483     Image
6  Linear Regression      Regression      6         9.0       2574     Image
7            XGBoost      Regression      6         3.8       6430     Image
8  Linear Regression      Regression      8         9.9       6166   Tabular
9  Linear Regression      Regression      3         0.8       4718      Text

In [33]:
# первые три строки
df.head(3)

           model            type  score  train_time  data_size data_type
0        XGBoost      Regression      3         9.8       1735   Tabular
1     Neural Net      Regression      3         1.7       2418      Text
2  Random Forest  Classification      7         3.6       9000     Image

In [40]:
df.columns[3]

'train_time'

In [35]:
# доступ к столбцам
df['model']

0              XGBoost
1           Neural Net
2        Random Forest
3        Random Forest
4                  KNN
5                  SVM
6    Linear Regression
7              XGBoost
8    Linear Regression
9    Linear Regression
Name: model, dtype: object

In [36]:
# еще доступ к столбцам
df['score']

0    3
1    3
2    7
3    9
4    4
5    5
6    6
7    6
8    8
9    3
Name: score, dtype: int64

In [ ]:
# доступ к строкам

In [ ]:
# выберите записи с помощью логических операций

In [ ]:
# получите список имен столбцов

In [ ]:
# добавьте еще один столбец

In [ ]:
# удалите этот столбец

#### Основные методы

`df.shape` — вывод количества строк и столбцов (кортеж).

`df.columns` — Index(количество стоблцов).

`df.info()` — общая информация о таблице.

`df.head(n)` — первые n строк (default — 5).

`df.tail(n)` — последние n строк (default — 5).

#### ПРАКТИКА 2
Выполни задание.

1. Добавь булевый столбец `окей`: `True`, если значение `score` больше 5 иначе `False`.
2. Выведи только те элементы, где значение столбца `окей` — `False`.
3. Поменяй название последнего стобца на `is_ok`.
4. Создай новый DataFrame `df_2`, в котором будут строки, у которых значения столбца `model` заканчивается буквой **t**. Для этого примени к столбцу конструнцию `.str`, после чего продолжай работать с ним как с обычной строкой.

In [ ]:
# 1

In [ ]:
# 2

In [ ]:
# 3

In [ ]:
# 4

#### Познакомьтесь с подвыборками DataFrame

Выполните ячейки кода с примерами ниже.

**Выбор одной строки**

In [ ]:
df.iloc[0]

**Выбор нескольких подряд идущих строк**

In [ ]:
df.iloc[1:4]

**Выбор нескольких строк**

In [ ]:
df.iloc[[1,3,5]]

**Выбор одного стобца**

In [ ]:
df['train_time']

**Выбор нескольких подряд идущих столбцов**

In [ ]:
# используем .loc и указываем выбор всех строк
df.loc[:, 'model':'score']

**Выбор конкретных стобцов**

In [ ]:
# используем двойные квадратные скобки
df[['model', 'score']]

**Выбор конкертных столбцов и нескольких подряд идущих строк**

In [ ]:
# используем .loc, первым значение указываем срез строк, затем список нужных стобцов
df.loc[1:4, ['model','score']]

**Выбор всех строк, которые подходят под условие**

In [ ]:
df[df['type'] == 'Classification']

## Работа с файлами

Функция **read_csv** загружает в DataFrame данные из файла.

Несколько параметров этой функции:

`sep` задаёт разделитель столбцов. По умолчанию — запятая, но часто встречается точка с запятой.

`dtype` позволяет заранее указать типы данных для столбцов через словарь.

`encoding` указывает кодировку файла.

`index_col` — номер столбца или имя, который станет индексом.

## Немного графиков

In [ ]:
# построим гистограмму по рейтингу

`.value_counts()` — один из самых полезных и мощных методов в pandas.

In [ ]:
# посмотрим, сколько бесплатных игр

In [ ]:
# Визуализируем результат.
# Для этого используем .plot(kind = 'тип графика').

## Работа с пропущенными значениями

В pandas для представления отсутствующих данных используется значение **NaN (Not a Number — не число).**

In [ ]:
# во всем DataFrame

In [ ]:
# в конкретном столбце

In [ ]:
# удаляем отсутствующие значения во всем DataFrame

In [ ]:
# заполняем отсутствующие значения во всем DataFrame

In [ ]:
# заполнение средними значениями

## Немного полезностей

Документация библиотеки: [клик](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html).

Подсказка: если поставить курсор внутрь скобок метода и нажать Tab, появится список подсказок. Если нажать Shift + Tab, откроется подробное описание метода или функции с объяснением параметров.

# Домашнаяя работа


Работаем с файлом **steam_games.csv**.

Выполни задания в ячейках ниже. См. комментарии.

- name — название игры.
- developers — разработчики игры.
- categories — категории игры.
- genres — жанры игры.
- required_age — минимальный возраст.
- n_achievements — количество достижений.
- platforms — доступные платформы.
- is_released — статус выпуска.
- release_date — дата выхода.
- additional_content — дополнительный контент.
- total_reviews — общее число отзывов.
- total_positive — положительные отзывы.
- total_negative — отрицательные отзывы.
- review_score — оценка на основе отзывов.
- metacritic — оценка Metacritic.
- is_free — указание на то, бесплатная игра или нет.
- price_initial (USD) — первоначальная цена в USD.

In [ ]:
df = pd.read_csv("steam_games.csv")
df.head(3)

## Основное задание

In [ ]:
# посчитай, сколько в сумме стоят все игры

In [ ]:
# посчитай средний рейтинг metacritic

In [ ]:
# посчитай средний рейтинг пользователей

In [ ]:
# найди максимальное количество достижений в игре

In [ ]:
# Построй точечный график по признакам review_score и price_initial (USD).
# Видны ли закономерности? Если да, то какие? Запиши ответ в текстовой ячейке.

In [ ]:
# Построй горизонтальную столбчатую диаграмму для признака platforms. Используй .value_counts().

In [ ]:
# Добавь в DataFrame столбец take_my_money со значениями 1 если игра имеет рейтинг > 8.
# Подсказка: удобнее всего это сделать через df[feature_name].apply(lambda x: ...).

## Задание на дополнительную оценку

In [ ]:
# Выведи количество строк и количество столбцов в датасете через пробел.

In [ ]:
# В каких столбцах пропущенных значений больше 470? Выведи список в столбик (только названия признаков).

In [ ]:
# Какие игры в среднем стоят дороже: с рейтингом 5 или с рейтингом 7?

In [ ]:
# Можно ли сказать, что если игра бесплатная, то у нее лучше рейтинг? Ответ объясни.

In [ ]:
# Какой процент игр еще не выпустили в релиз? Ответ округли до двух знаков после запятой.

# Часть 2 (Занятие 6)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Самостоятельная практика

Загрузи файл данных `positions.csv`.

В нём содержится информация о сотрудниках компании company_name, основанной в 2012 году. В 2020 году компания провела масштабный набор сотрудников.

Тебе предстоит выполнить несколько заданий. **Результаты заноси в тест в Информатиксе.**

In [ ]:
df = pd.read_csv("positions.csv")
df

In [ ]:
# Сколько людей имеют опыт более 7 лет?

In [ ]:
# Посчитайте среднюю зарплату в компании.

In [ ]:
# Сколько в компании Алексеев, которые работают на удалёнке?

In [ ]:
# Специалистов какой должности больше всего в компании?

In [ ]:
# Сколько сотрудников получает зарплату выше медианной?
# Для нахождения медианы используй np.median().

In [ ]:
# Для выполнения этого задания тебе придется посчитать сколько людей с каким именем работает в компании.
# Например: 3 Ивана, 4 Юлии, 1 Никита, 1 Олег.

# Найди два самых популярных и два самых редких имени, а затем определи средний опыт работы этих двух групп.
# Например, средний опыт Иванов и Юлий - 4 года, а средний опыт Никит и Олегов - 2 года.

# В ответе запиши два числа через пробел (сначала для самых популярных имен, затем для самых редких).

## Ещё несколько очень полезных инструментов

### Сортировка

In [ ]:
df = pd.read_csv("steam_games.csv")
df

Сортировка значений

Сортировка по индексу

### Агрегирование данных и групповые операции

В анализе данных часто используется группировка — разделение датасета на группы с последующим вычислением агрегатных показателей, таких как среднее или сумма, для каждой группы.

**Группировки**

In [ ]:
# Чаще всего нас интересует только один столбец.

**Собственные функции**

In [ ]:
# Напиши свою функцию, например, для вычисления разности среднего и медианного значений (по модулю).

In [ ]:
# Если интересен только один столбец, не обязательно группиповать весь df.

## Нужно больше практики!

Работаем с файлом **steam_games.csv**.

Визуализируем, анализируем, генерируем.

**Начнем с анализа**

In [ ]:
df

In [ ]:
# 1. Топ-10 самых популярных игр по количеству положительных отзывов.
# Подсказка: для красивого вывода используй сепаратор.

In [ ]:
# 2. Топ-3 самых дорогих в среднем категорий (category_1) игр.

In [ ]:
# 3. В каком жанре (genre_1) в среднем больше всего достижений?

In [ ]:
# 4. Какой % игр выпускается для mac?

In [ ]:
# 5. Какой разработчик выпустил больше всего игр?

In [ ]:
# 6. Какой % игр имеет хотя бы на 10 положительных отзывов больше, чем отрицательных?

In [ ]:
# 7. Сколько игр стоимостью меньше 1$ выпустили в 2023 году?
# Подсказка: используй feature.str.startswith().

# Часть 3 (Занятие 7)

**Сгенерируем пару новых признаков и продолжим анализировать**.

In [ ]:
df

In [ ]:
# 8. Какие признаки можно разделить/изменить, чтобы с ними было удобно работать?

In [ ]:
 #9. Создай новые признаки (из задания 8).

In [ ]:
# 9.1

In [ ]:
# 9.2

In [ ]:
# 10. В каком месяце чаще всего выпускают игры?

In [ ]:
# 11. Какая игра из тех, что вышли весной и поддерживают все платформы, имеет наибольшее количество отзывов?

In [ ]:
# 12. Каких игр поддерживающих все платформы и вышедших летом было больше: платных или бесплатных?

**Пора что-нибудь нарисовать!**

Не забывайте: графики должны быть понятными!

Подсказка, как делать графики прямо из pandas: [тык](https://pandas.pydata.org/docs/user_guide/visualization.html).

In [ ]:
# 13. Изобрази распределение игр из задания 12 с помощью круговой диаграммы.

In [ ]:
# 14. Изобрази распределение категорий игр из задания 2 с помощью столбчатой диаграммы: игры каких категорий сколько стоят в среднем?

In [ ]:
# 15. Построй гистограммы для четырех самых популярных жанров (genre_1) по признаку стоимость. Учитывать только игры дешевле 30$.

In [ ]:
# 16. Построй точечный график зависимости количества достижений от года выпуска игры. Есть ли закономерности?

**Еще немного генерации**

In [ ]:
# 17*. Какой признак/признаки ты бы добавил? Почему?

In [ ]:
# 18*. Добавь его/их и визуализируй (если этот признак можно получить из уже имеющихся).